# Generated by Django 3.2.7 on 2021-09-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
